### ISSUE TITLE
Cargo workspace member list formatted on a single line

### ISSUE THREAD

**Issue by luckysori** [tbrand/cargo-tomlfmt#12]
If you run `cargo tomlfmt` on a `Cargo.toml` file which configures a workspace, the list of members of the workspace is formatted to be on a single line. E.g.
``` toml
[workspace]
members = [ "crate1", "crate2" ] 
```
It would be preferable to keep each member on separate lines, either by default or via configuration. E.g.
``` toml
[workspace]
members = [ 
    "crate1", 
    "crate2" 
] 
```
