### ISSUE TITLE
`Error: ValueAfterTable`

### ISSUE THREAD

**Issue by tbrand** [tbrand/cargo-tomlfmt#4]
I think this is a valid toml format but it raises the error.
```toml
[package]
name = "dummy"
version = "0.1.0"

[dependencies]
some = "0.1"
other = { version = "^0.4" }
```
